services:
    app:
        build: .
        container_name: laravel_frankenphp
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: db_investasi
        restart: always
        environment:
            MYSQL_DATABASE: db_investasi
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: ""
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
